# Stage 1: Build React Frontend
FROM node:16-alpine AS frontend-builder
WORKDIR /app/Frontend
COPY Frontend/package*.json ./
RUN npm install --legacy-peer-deps
COPY Frontend/ ./
RUN npm run build

# Stage 2: Serve Backend & Frontend
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .

# Build ఫైల్స్ మొత్తం (public images తో సహా) కాపీ చేయడం
COPY --from=frontend-builder /app/Frontend/build ./frontend/build
COPY --from=frontend-builder /app/Frontend/build ./Frontend/build

EXPOSE 5001
ENV NODE_ENV=production
ENV PORT=5001

CMD ["node", "backend/server.js"]
